Repository syl20bnr/spacemacs, pull requests merged in 2018-10, with the labels that each got.

#5488 Achievement/cobra
  doc/DOCUMENTATION.org
Labels: Proposal

#11437 [TravisCI] Add documentation autofixer
  .travis.yml
  .travisci/pub_html.sh
  .travisci/pub_org_fmt.sh
  .travisci/pub_prep.sh
  .travisci/test.sh
Labels: Tests

#11491 Fix code blocks
  layers/+lang/c-c++/README.org
Labels: Documentation ✏

#11508 Flattening documentation tools
  .circleci/config.yml
  .circleci/validoc/format
  .travis.yml
  .travisci/pub_org.sh
Labels: DO NOT MERGE, Documentation ✏, WIP
